In [5]:
import pandas as pd
import numpy as np

In [6]:
cars=pd.read_csv("/Users/abhinavbadwekar/Downloads/quikr_car.csv")

In [7]:
backup=cars.copy()

In [8]:
cars.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [9]:
pd.isnull(cars).sum()

name           0
company        0
year           0
Price          0
kms_driven    52
fuel_type     55
dtype: int64

In [10]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

In [11]:
cars=cars[cars['year'].str.isnumeric()]

In [12]:
cars['year']=cars['year'].astype(int)

In [13]:
cars.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [14]:
cars=cars[cars['Price']!="Ask For Price"]

In [15]:
cars['Price']=cars['Price'].str.replace(',','')

In [16]:
cars['Price']=cars['Price'].astype(int)

In [17]:
cars['kms_driven']=cars['kms_driven'].str.split(' ').str.get(0).str.replace(',','')

In [18]:
cars=cars[cars['kms_driven'].str.isnumeric()]

In [19]:
cars['kms_driven']=cars['kms_driven'].fillna(0)

In [20]:
cars['kms_driven']=cars['kms_driven'].astype(int)

In [21]:
cars.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,45000,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,28000,Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,36000,Diesel
6,Ford Figo,Ford,2012,175000,41000,Diesel

In [22]:
cars=cars[~cars['fuel_type'].isna()]

In [23]:
cars['name']=cars['name'].str.split(' ').str.slice(0,3).str.join(' ')

In [24]:
cars.head()

                     name   company  year   Price  kms_driven fuel_type
0     Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1     Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
3       Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
4  Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
6               Ford Figo      Ford  2012  175000       41000    Diesel

In [25]:
cars=cars.reset_index(drop=True)

In [26]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    object
 1   company     816 non-null    object
 2   year        816 non-null    int64
 3   Price       816 non-null    int64
 4   kms_driven  816 non-null    int64
 5   fuel_type   816 non-null    object
dtypes: int64(3), object(3)
memory usage: 38.4+ KB

In [27]:
cars=cars[cars['Price']<6e6].reset_index(drop=True)

In [28]:
cars.describe()

              year         Price     kms_driven
count   815.000000  8.150000e+02     815.000000
mean   2012.442945  4.017933e+05   46277.096933
std       4.005079  3.815888e+05   34318.459638
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.900000e+05   56879.000000
max    2019.000000  3.100000e+06  400000.000000

In [29]:
cars

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
811          Tata Indica V2      Tata  2009  110000       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
813            Tata Zest XM      Tata  2018  260000       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[815 rows x 6 columns]

In [30]:
cars.to_csv("cleaned car dataset.csv")

In [31]:
x=cars.drop(columns='Price')

In [32]:
y=cars['Price']

In [33]:
x

                       name   company  year  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006          40    Diesel
2         Hyundai Grand i10   Hyundai  2014       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014       36000    Diesel
4                 Ford Figo      Ford  2012       41000    Diesel
..                      ...       ...   ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011       50000    Petrol
811          Tata Indica V2      Tata  2009       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009      132000    Petrol
813            Tata Zest XM      Tata  2018       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013       40000    Diesel

[815 rows x 5 columns]

In [34]:
y

0       80000
1      425000
2      325000
3      575000
4      175000
        ...
810    270000
811    110000
812    300000
813    260000
814    390000
Name: Price, Length: 815, dtype: int64

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=661)

In [37]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [38]:
ohe=OneHotEncoder()
ohe.fit(x[['name','company','fuel_type']])

OneHotEncoder()

In [39]:
column_trans = make_column_transformer(( OneHotEncoder(categories=ohe.categories_),['name','company','fuel_type']),remainder='passthrough')

In [40]:
from sklearn.linear_model import LinearRegression

In [41]:
lr=LinearRegression()

In [42]:
pipe=make_pipeline(column_trans,lr)

In [43]:
pipe.fit(x_train,y_train)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/compose/_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [44]:
pipe.predict(x_test)

array([1488093.28685759,  609143.16033675,  365094.60621702,
        570370.33732735,  609482.07726996,  647037.10162812,
        497095.22561175,   78696.24615982,  542151.57399303,
        391378.19914081,  233125.91616508,  107553.54661072,
        379250.98379871,  462990.27822447,   27391.71557461,
        384409.96684907,  295353.77253959,  355129.28538338,
       2090268.82654808,  530652.52885796,  290733.34740519,
        436095.02384929,  185170.30840255,   26046.83820634,
       1906236.17216038,  568670.90944452,  184248.2862839 ,
        165097.61478385,  501387.6268468 ,  535324.62010122,
        229720.45606566, 1500461.01100184, 1132802.88999756,
        364620.7476641 ,  437072.57307235,  490155.80948181,
        175285.23649773,  237277.10575421,  411579.56346089,
       1122502.32954171,  407182.35813087,  305132.91341858,
        165097.61478385,  673488.88745283,  117572.31167061,
        233343.47457404,  461455.60310289,  390527.81141847,
        254565.82435712,  286690.07309761,  586870.48280656,
        300998.33267622,  377868.08705309,  384024.16187433,
        270525.84695108,   78696.24615982,  137126.78648973,
        673488.88745283,  159489.20200325,  405169.41619477,
        284771.42656752,  660618.1212391 ,  260280.21965362,
        -46716.05595629,  370586.03518799,  357319.67974801,
        376546.4385794 ,  442031.30485898,  237277.10575421,
        384409.96684907,  490915.8947176 ,  210500.61950074,
        829288.01650707,  288078.32804552,  483556.49425086,
        615444.94957507,  233778.37622091,  170960.04282039,
         44876.67213974,  430251.4807899 ,  363211.95832258,
        242373.91947969,  323903.7481416 ,  301841.53297844,
        597259.47065681,  606943.30838156,  217414.86156495,
        265742.58376969,  597762.65439126, 1675900.61643834,
        858466.38877711,  420944.14887235,  149492.04879535,
        450299.78126313,  166857.96005098,   -5934.89367252,
        203413.85054464,  677025.77295501,  532260.18994975,
        164746.46787476,  230278.84984534,  227119.18426178,
        111361.54797556,  336181.44891595,  673488.88745283,
        526571.59459577,   82667.12177673,  600687.30613932,
        306906.02143458,  424230.96025597,  365697.65558734,
        540663.78635658,  686399.71182859,  571696.1183003 ,
        455768.55353863,  279837.81564059,  209517.51388944,
        561080.0884446 ,  257329.70353134,   96104.78710067,
        672122.75974504,  326402.271122  ,   30832.1517368 ,
        611358.87794264,  655526.87069669,  596922.99703747,
        396284.99605001,  517598.91248202,  104971.80654031,
        126436.99406451, 2090268.82654808,   78696.24615982,
        300425.36650903,  -68264.29149   ,  509072.41459969,
        477677.38897566,  292053.34547009,  119116.08360981,
        557786.40006316,  352885.9892523 ,  218120.2045429 ,
        286690.07309761,  529366.69419942,  433053.62228122,
        734087.30808531,   93620.97721905,  528385.94975215,
        230133.9150927 ,  175285.23649773,  340932.20162768,
         75972.77238655,  571696.1183003 ,   73269.51310878,
        609143.16033675,   93583.79102389, 2090268.82654808,
         75700.77228906,  967485.20440261,  357812.01462423,
        358109.65006268,  181193.36665801,  305132.91341858,
        211588.6198907 ,  627315.99450997,  425955.39428677,
        523996.81770327,   67164.52494357,  177172.435926  ,
        653843.88312218,  306725.09567906,  497847.43816694,
        284107.66037845,  256159.43923571,  204811.11506404,
        425411.39409178,  694779.09790434,  284814.32687565,
       1503181.01197672,  333914.54056621,  591912.28139023,
        324866.34100841,  192716.94735867, 1182001.94016927,
         95832.78700317,  251313.22272821,  160352.03901833,
        271409.37177285, 2090268.82654808,  407711.87825118,
        366798.48169293,  -40182.4975222 ,  292820.79401224,
        285549.81768785,  262771.03200381,  196940.24822441,
        416270.40415488,  203732.10953756,  154136.28807192,
        211554.31785893,  533538.58213489,  355401.28548087,
         45368.56532521,  303129.24097722,   46073.13239055])

In [45]:
from sklearn.metrics import r2_score

In [46]:
r2_score(y_test,pipe.predict(x_test))

0.7966430184466151

In [47]:
import pickle

In [48]:
pickle.dump(pipe,open('LinearRegressionModel.pkl','wb'))

In [49]:
pipe.predict(pd.DataFrame([['Maruti Suzuki Ritz','Maruti',2011,50000,'Petrol']],columns = ['name','company','year','kms_driven','fuel_type']))

array([257891.05583431])

In [ ]:
from flask import Flask,render_template,request,redirect
from flask_cors import CORS,cross_origin
import pickle
import pandas as pd
import numpy as np

app=Flask(__name__)
cors=CORS(app)
model=pickle.load(open('LinearRegressionModel.pkl','rb'))
car=pd.read_csv('cleaned car dataset.csv')

@app.route('/',methods=['GET','POST'])
def index():
    companies=sorted(car['company'].unique())
    car_models=sorted(car['name'].unique())
    year=sorted(car['year'].unique(),reverse=True)
    fuel_type=car['fuel_type'].unique()

    companies.insert(0,'Select Company')
    return render_template('index.html',companies=companies, car_models=car_models, years=year,fuel_types=fuel_type)


@app.route('/predict',methods=['POST'])
@cross_origin()
def predict():

    company=request.form.get('company')

    car_model=request.form.get('car_models')
    year=request.form.get('year')
    fuel_type=request.form.get('fuel_type')
    driven=request.form.get('kilo_driven')

    prediction=model.predict(pd.DataFrame(columns=['name', 'company', 'year', 'kms_driven', 'fuel_type'],
                              data=np.array([car_model,company,year,driven,fuel_type]).reshape(1, 5)))
    print(prediction)

    return str(np.round(prediction[0],2))



if __name__=='__main__':
    app.run()

In [ ]:
import streamlit as st
import pandas as pd
import numpy as np
import pickle 

#TITLE
st.title("Predict the price of your used car")

cars=pd.read_csv("/Users/abhinavbadwekar/Documents/python/cleaned car dataset.csv")
model=pickle.load(open('LinearRegressionModel.pkl','rb'))



def predict(company,model,year,kms_driven,fuel_type):
   prediction=model.predict(pd.DataFrame(columns=[ 'company', 'name', 'year', 'kms_driven', 'fuel_type'],
                                         data=np.array([company,model,year,kms_driven,fuel_type]).reshape(1, 5)))
   print(prediction)
   return str(np.round(prediction[0],2))

def main():
   st.write("Fill the details")
   company = st.selectbox('Company', cars['company'].unique())
   model = st.selectbox('Model',cars['name'].unique())
   year = st.selectbox('Year', cars['year'].unique())
   kms_driven = st.selectbox('kms_driven', cars['kms_driven'].unique())
   fuel_type = st.selectbox('Fuel Type', cars['fuel_type'].unique())
   prediction = ""
   if st.button('Predict'):
      predict=predict(company,model,year,kms_driven,fuel_type)
   st.success(prediction)   
if __name__ =='__main__':
   main()